package ian.projects.backend.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Entity class representing a Book in the system. This class is mapped to the
 * "books" table in the database. It contains the basic attributes of a
 * bookstore product.
 */
@Entity
@Table(name = "books")
public class Book {

	/**
	 * Unique identifier of the book. Automatically generated by the database.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int bookCode;

	/**
	 * Author of the book.
	 */
	@Column
	private String author;

	/**
	 * Title of the book.
	 */
	@Column
	private String title;

	/**
	 * Price of the book.
	 */
	@Column
	private String price;

	public int getBookCode() {
		return bookCode;
	}

	public void setBookCode(int bookCode) {
		this.bookCode = bookCode;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

}
